#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------

# Overall title for the Workshop.
title: "Sistemi di elaborazione dell'Informazione I"

#------------------------------------------------------------
# Generic settings 
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "workshop"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
repository: <USERNAME>/<PROJECT>

# Email address, no mailto:
email: "visconti@di.unito.it"


# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Turn on built-in syntax highlighting.
highlighter: rouge
